<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getGameByEvent($event){
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $games = $qb->select('g')
                ->from('AppBundle:Game','g')
                ->leftJoin('g.events', 'e')
                ->leftJoin('g.scores', 's')
                ->where('e = :event')
                ->setParameter('event', $event);
        
        return $games->getQuery()->getResult();
    }
}
