<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceReservationRepository extends EntityRepository
{
    public function getDayReservation($placeId, $startDate, $endDate)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $startDate->setTime(0,0,0);
        $endDate->setTime(23,59,59);

        $qb->select('r')
                ->from('AppBundle:PlaceReservation', 'r')
                ->leftJoin('r.place', 'p')
                ->where('p.id = :id')
                ->andWhere('r.data > :startDate')
                ->andWhere('r.data < :endDate')
                ->setParameter('id', $placeId)
                ->setParameter('startDate', $startDate)
                ->setParameter('endDate', $endDate)
                ->orderBy('r.data', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
