<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{

    public function searchPlacesByCity($city)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
                ->from('AppBundle:Place', 'p')
                ->where('p.city LIKE :city')
                ->setParameter('city', '%' . $city . '%')
                ->orderBy('p.name', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function searchPlacesByCategory($category)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
                ->from('AppBundle:Place', 'p')
                ->leftJoin('p.category', 'c')
                ->where('c.name LIKE :category')
                ->setParameter('category', '%' . $category . '%')
                ->orderBy('p.name', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function searchPlacesByCityAndCategory($city, $category)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
                ->from('AppBundle:Place', 'p')
                ->leftJoin('p.category', 'c')
                ->where('c.name LIKE :category')
                ->andWhere('p.city LIKE :city')
                ->setParameter('city', '%' . $city . '%')
                ->setParameter('category', '%' . $category . '%')
                ->orderBy('p.name', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getPlacesCities()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('DISTINCT p.city')
                ->from('AppBundle:Place', 'p');

        return $qb->getQuery()->getResult();
    }
    
    public function getSinglePlace($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
                ->from('AppBundle:Place', 'p')
                ->leftJoin('p.reservation', 'r')
                ->where('p.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }

}
