imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    
easy_admin:
    entities:
        - AppBundle\Entity\Event
        - AppBundle\Entity\Category
        - AppBundle\Entity\User
        
knp_paginator:
    template:
        pagination: paginator.html.twig

hwi_oauth:
   connect:
        account_connector: app.user.provider
   firewall_name: main
   fosub:
       username_iterations: 30
       properties:
           facebook: facebookId
   resource_owners:       
       facebook:
           type: facebook
#           client_id: "%facebook_app_id%"
#           client_secret: "%facebook_app_secret%"
           client_id : 774676639212191
           client_secret: b0c5c4bbc440ad590451e0a3483367b7
           scope:         "email"
           options:
               display: popup    
               
services:
    fos_user.doctrine_registry:
        alias: doctrine
        
    app.user.provider:
        class: "AppBundle\Service\FOSUserProvider"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]

liip_imagine:
    resolvers:
        default:
            web_path:
              web_root: %kernel.root_dir%/../web
              cache_prefix: media/cache

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/images/teams

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        event_image_thumb:
            quality: 75
            filters:
                thumbnail: { size: [290, 100], mode: outbound }
        event_image:
            quality: 75
            filters:
                thumbnail: { size: [1000, 200], mode: outbound }
        team_image_big:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        team_image_small:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
                
vich_uploader:
    db_driver: orm
    mappings:
        event_image:
            uri_prefix:         /images/events
            upload_destination: %kernel.root_dir%/../web/images/events
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        user_image:
            uri_prefix:         /images/users
            upload_destination: %kernel.root_dir%/../web/images/users
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        team_image:
            uri_prefix:         /images/teams
            upload_destination: %kernel.root_dir%/../web/images/teams
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            
payum:
    security:
        token_storage:
            AppBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        AppBundle\Entity\Payment: { doctrine: orm }
        AppBundle\Entity\PaymentDetails: { doctrine: orm }

    gateways:
        offline:
            offline: ~